---
- name: install apache
  yum:
    name: httpd
    state: latest
    update_cache: yes
  
- name: "install index page"
  copy:
    src: file/index.html
    dest: /var/www/html/index.html
    backup: yes
- name: "service start"
  service:
    name: httpd
    state: started